---
title: "Main_figs"
author: "John Gardner"
date: "October 16, 2020"
output: html_document
---

```{r setup, include=FALSE}



knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}





```

## Including Plots

You can also embed plots, for example:

```{r Fig1, echo=FALSE}

# great lakes https://www.sciencebase.gov/catalog/item/530f8a0ee4b0e7e46bd300dd

ogrListLayers("D:/GIS/WBD/wbdhu2.gdb")

huc2 <- sf::st_read("D:/GIS/WBD/wbdhu2.gdb", layer = "WBDHU2") %>% #, type=3)  %>%
 # st_transform(crs=2163) %>%
  filter(huc2 %in% c("01", "02", "03", "04", "05", "06", "07", "08", "09","10", "11", "12", "13", "14", "15", "16", "17", "18")) %>%
  mutate(HUC2 = as.character(huc2)) %>%
  mutate(basin = case_when(
    HUC2 %in% c("05","06", "07", "08", "10", "11") ~ "Miss",
    HUC2 %in% c("14", "15") ~ "Colorado",
    TRUE ~ HUC2
  )) %>%
  #mutate(valid = st_is_valid(.))%>%
 # filter(!is.na(valid)) %>%
  group_by(basin) %>%
  summarise(geometry = st_union(Shape)) %>%
  ungroup()

huc2 <-  sf::st_read("G:/wbdhu2_a_us_march2017.gdb", layer="WBDHU2") %>%
    filter(HUC2 %in% c("01", "02", "03", "04", "05", "06", "07", "08", "09","10", "11", "12", "13", "14", "15", "16", "17", "18")) %>%
  mutate(HUC2 = as.character(HUC2)) %>%
  mutate(basin = case_when(
    HUC2 %in% c("05","06", "07", "08", "10", "11") ~ "Miss",
    HUC2 %in% c("14", "15") ~ "Colorado",
    TRUE ~ HUC2
  )) %>%
  sf::st_make_valid() %>%
  st_transform(2163) %>%
  st_buffer(10) %>%
  group_by(basin) %>%
  summarise() %>%
  ungroup() 


huc2_usa <- st_intersection(huc2 %>% st_transform(4326), usa %>% 
                              st_transform(4326) %>%
                              st_make_valid())

flowline %>%
  st_set_geometry(NULL) %>%
  inner_join(trends_tss_annual, by= "ID") %>%
  mutate(trend_median_05 = ifelse(is.na(trend_median_05), "none", trend_median_05)) %>%
  group_by(Tidal, trend_median_05) %>%
  dplyr::summarise(n=n(), length= sum(LENGTHKM_)) %>%
  mutate(sum= sum(n), perc = n/sum, sum_len=sum(length), perc_len=length/sum_len)
  
flowline %>%
  st_set_geometry(NULL) %>%
  inner_join(trends_tss_annual, by= "ID") %>%
  mutate(trend_mean_05 = ifelse(is.na(trend_mean_05), "none", trend_mean_05)) %>%
  group_by(trend_mean_05) %>%
  dplyr::summarise(n=n(), length= sum(LENGTHKM_)) %>%
  mutate(sum= sum(n), perc = n/sum, sum_len=sum(length), perc_len=length/sum_len)


ggplot() +
  geom_sf(data=usa %>%
            st_transform(2163), fill="black", color="black") +
  geom_sf(data=flowline_trend %>%
            filter(Tidal==0, trend_median_05=="none"), color="grey40")+
  geom_sf(data=flowline_trend %>%
            filter(Tidal==0, trend_median_05 != "none") ,  aes(color=trend_median_05))+
    geom_sf(data=flowline_trend %>%
            filter(Tidal==1)  %>%
              filter(trend_median_05 != "none") %>%
            st_point_on_surface(),  aes(color=trend_median_05),  size=1.3,  pch=21, fill="white") +
  theme_bw() +
  scale_color_manual(values =c("deepskyblue1", "gold", "grey70")) +
    theme(legend.position = c(0.98, 0.29),
    line = element_blank(), 
    rect = element_blank(), 
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    plot.background = element_blank(),
    legend.text = element_text(size=9),
    legend.title = element_blank()) #+


ggsave("D:/Dropbox/projects/riverTSS/figs/Fig1_tss_3.31_nohuc.png", width=6, height=3, units="in", dpi=350)


###########################

flow_trends <- read_feather("D:/Dropbox/projects/riverTSS/out/flow_annual_trends_v1.feather") %>%
  left_join(flowline_full %>%
              st_set_geometry(NULL), by="COMID") %>%
  mutate(river_size = ifelse(is.na(LevelPathI),"<60",">60")) %>%
  mutate(trend_median_05 = ifelse(is.na(trend_median_05), "none", trend_median_05))

flow_trends %>%
  group_by(river_size, trend_mean_05) %>%
  summarise(n=n()) %>%
  mutate(sum= sum(n), perc = n/sum)
  
flow_trends_sf <- flow_trends %>%
  filter( long >-135 & lat >22) %>%
  filter(!is.na(lat) & !is.na(long)) %>%
  st_as_sf(coords=c(x="long", y="lat"), crs=4326) %>%
  st_transform(2163)

ggplot() +
  geom_sf(data=usa %>%
            st_transform(2163), fill="black", color="black") +
  geom_sf(data=flow_trends_sf %>%
            filter(trend_median_05=="none"), aes( shape=as.factor(river_size), size=as.factor(river_size)), color="grey70", alpha=0.4) +
  geom_sf(data=flow_trends_sf %>%
            filter(trend_median_05!="none"), aes(color=trend_median_05, shape=as.factor(river_size), size=as.factor(river_size)), alpha=0.9) +
 scale_shape_manual(values=c(16, 17)) +
 scale_size_manual(values=c(0.4,1.7)) +
 scale_color_manual(values =c("deepskyblue1", "gold", "grey70")) +
    theme(legend.position = "none",
    line = element_blank(), 
    rect = element_blank(), 
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    plot.background = element_blank(),
    legend.text = element_text(size=9),
    legend.title = element_blank()) 

ggsave("D:/Dropbox/projects/riverTSS/figs/Fig1_flow_3.31_nohuc.png", width=6, height=3, units="in", dpi=350)


# load county and nri_trend

county_trend <-county %>%
  left_join(nri_trend, by="Fips")

ggplot()+
  geom_sf(data=usa %>%
            st_transform(2163), fill="black", color="black") +
  geom_sf(data=county_trend %>%
            filter(!is.na(trend_erosion_05)) %>%
            st_transform(2163), 
          aes(fill=trend_erosion_05), color="transparent", alpha=0.9) +
  scale_fill_manual(values =c("deepskyblue1", "gold"), name="Soil Loss") +
    theme(legend.position = c(0.99, 0.31),
    line = element_blank(), 
    rect = element_blank(), 
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    plot.background = element_blank(),
    legend.text = element_text(size=9)) 

ggsave("D:/Dropbox/projects/riverTSS/figs/Fig1_erosion_3.31_nohuc.png", width=6, height=3, units="in", dpi=350)

```

```{r Fig2}

# load tss_sum_year_join
# load flagges reaches
# load nabd2
#load path_sum

tss_sum_year_plot <- tss_sum_year_join %>%
  left_join(flag_reaches, by="ID") %>%
  mutate(tss_median = ifelse(is.na(flag), tss_median, NA)) %>%
  group_by(LvlPthI, year) %>%
  arrange(Pthlngt) %>%
  ungroup() %>%
  filter(LvlPthI !=630001920 ) %>%
  filter(Name %in% c("Colorado River",  "Arkansas River","Yellowstone River",  "Columbia River", "Mississippi River", "Missouri River")) %>%
  filter(LvlPthI== 720000024 & Pthlngt > 70 | LvlPthI %in% c(50001315,350002977,550000017, 590001280, 350009839 ) & Pthlngt > 0) %>%
  mutate(trend = ifelse(Name=="Missouri River", "p>0.05", "p<0.05")) %>%
  group_by(LvlPthI) %>%
  mutate(Pthlngt = Pthlngt- min(Pthlngt)) %>%
  ungroup() %>%
  filter(LvlPthI== 350009839 & Pthlngt <1200 | LvlPthI %in% c(50001315,350002977,550000017, 590001280, 720000024) & Pthlngt < 10000)


plot_sum <- tss_sum_year_join %>%
  left_join(flag_reaches, by="ID") %>%
  mutate(tss_median = ifelse(is.na(flag), tss_median, NA)) %>%
  group_by(LvlPthI, year) %>%
  arrange(Pthlngt) %>%
  ungroup() %>%
  filter(LvlPthI !=630001920 ) %>%
  filter(Name %in% c("Colorado River",  "Arkansas River","Yellowstone River",  "Columbia River", "Mississippi River", "Missouri River")) %>%
  filter(LvlPthI== 720000024 & Pthlngt > 70 | LvlPthI %in% c(50001315,350002977,550000017, 590001280, 350009839 ) & Pthlngt > 0) %>%
  mutate(trend = ifelse(Name=="Missouri River", "p>0.05", "p<0.05")) %>%
  filter(LvlPthI== 350009839 & Pthlngt <1200 | LvlPthI %in% c(50001315,350002977,550000017, 590001280, 720000024) & Pthlngt < 10000) %>%
  group_by(LvlPthI) %>%
  summarise(min_tss_path = min(Pthlngt, na.rm=T),
                        max_tss_path = max(Pthlngt, na.rm=T))


dam_plot <- nabd2 %>%
  inner_join(flowline_full %>%
                           st_set_geometry(NULL) %>%
                           select(COMID, LevelPathI, Pathlength), by= "COMID") %>%
  filter(LevelPathI %in% tss_sum_year_plot$LvlPthI) %>%
  left_join(plot_sum, by=c("LevelPathI"="LvlPthI")) %>%
  group_by(LevelPathI) %>%
  mutate(Pathlength = Pathlength- min_tss_path) %>%
  ungroup() %>%
  inner_join(path_sum, by = "LevelPathI") %>%
  mutate(LvlPthI = LevelPathI) %>%
  filter(Pathlength < max_tss_path) %>%
  filter(Name=="Missouri River" & Pathlength>1000 | Name %in% c("Colorado River",  "Arkansas River","Yellowstone River",  "Columbia River", "Mississippi River") & Pathlength>=0) %>%
  mutate(y = case_when(
    Name=="Arkansas River" ~10,
    Name=="Colorado River" ~3,
    Name=="Columbia River"~1.5,
    Name== "Mississippi River" ~ 5,
    Name== "Missouri River" ~3))


# tennessee, Apalachiodol, arkansas, Ohio
ggplot()+
  geom_line(data= tss_sum_year_plot, aes(x=Pthlngt, y=tss_median, group=year, color=year), lwd=0.5, alpha=0.6)+
  scale_y_log10() +
  scale_x_reverse() +
  scale_color_viridis(discrete = F, option="C") +
  geom_point(data=dam_plot,
             aes(x=Pathlength, y=y), shape=17)+
  facet_wrap(~Name, scales="free") +
  
  
  theme_bw() +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        legend.position = c(0.19, 0.93),
        legend.direction = "horizontal",
        legend.background = element_blank(),
        axis.title = element_text(size=10),
        axis.text =  element_text(size=9),
        strip.text  = element_text(size=9),
        plot.title = element_text(size = 12, face = "bold")) +
  xlab("Distance from mouth (km)") +
  ylab("TSS (mg/L)") +
  guides(colour=guide_colorbar(barwidth = 5.7, barheight = 0.5,
                               title="",
                               ticks.colour = "black",
                                ticks.linewidth = 1,
                                frame.colour = "black")) 

#ggsave("D:/Dropbox/projects/riverTSS/figs/Fig2_profiles_3.30.png", width=7, height=4, units="in", dpi=300)

tss_profile_trends %>%
  group_by(mean_prof_trend) %>%
  summarise(n=n()) %>%
  mutate(p = n / sum(n))

```


```{r Fig3}

ggplot()+
  geom_sf(data=usa, fill="black", color="transparent") +
  geom_sf(data=flowline_huc4 %>%
            filter(trend_median_05 %in% c(NA, "increasing")) %>%
            st_transform(2163), 
          color="grey40", lwd=0.2) +

  geom_sf(data=flowline_huc4 %>%
            filter(trend_median_05 =="decreasing") %>%
            filter(!is.na(driver)) %>%
            st_transform(2163),
          aes(color=driver)) +
 scale_color_manual(values = c("#FDC086", "#386CB0","#BEAED4","#F0027F","#BF5B17", "#FFFF99", "#7FC97F" )) +
  # scale_color_brewer(palette = "Accent", na.value="grey") +
   theme( legend.position = c(1,0.25),
    legend.background = element_rect(fill="black"),
    line = element_blank(), 
    rect = element_blank(), 
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    plot.background = element_blank(),
    legend.text = element_text(size=6, color = "white"),
    legend.title = element_blank(),
    #legend.key.size = unit(2, "cm"),
    legend.key.height = unit(0.25, "cm")) +
   guides(color = guide_legend(override.aes = list(size = 2)))
  #  guides(color = guide_legend(keyheight=5))
       
   
#ggsave("D:/Dropbox/projects/riverTSS/figs/tss_drivers_v2.png", width=6, height=3, units="in", dpi=350)

ggplot(flowline_huc4 
       %>% st_set_geometry(NULL) %>%
            filter(trend_median_05 =="decreasing") %>%
            filter(!is.na(driver))) +
  geom_density(aes(abs(sen_tss_median), fill=driver), color="black", alpha=0.5) +
  theme_bw()+
  scale_x_log10()

flowline_huc4$driver <- factor(flowline_huc4$driver, levels = c("flow", "flow+erosion", "erosion", "flow+dams", "flow+erosion+dams","erosion+dams", "dams" ))

flowline_huc4  %>% 
  st_set_geometry(NULL) %>%
  filter(trend_median_05 =="decreasing") %>%
  filter(!is.na(driver)) %>%
  group_by(driver) %>%
  summarise(mean=mean(sen_tss_median, na.rm=T),
            med=median(sen_tss_median, na.rm=T), 
            sd=sd(sen_tss_median, na.rm=T),
            n=n()) %>%
  arrange(med)


library(ggridges)
library(EnvStats)

ggplot(flowline_huc4 %>%
         st_set_geometry(NULL) %>%
            filter(trend_median_05 =="decreasing") %>%
            filter(!is.na(driver)),
       aes(y=driver, x=abs(sen_tss_median), fill=driver)) +
  geom_density_ridges( color="black", alpha=0.95) +
  theme_bw()+
   scale_fill_manual(values = c("#FDC086", "#386CB0","#BEAED4","#F0027F","#BF5B17", "#FFFF99", "#7FC97F" )) +
  # scale_fill_brewer(palette = "Accent", na.value="grey") +
  scale_x_log10() +
  xlab("Rate of change (mg/L/yr)") +
  ylab("") +
  theme(legend.position = "none",
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()) # +
  # geom_text(data=flowline_huc4 %>%
  #        st_set_geometry(NULL) %>%
  #           filter(trend_median_05 =="decreasing") %>%
  #           filter(!is.na(driver)) %>% 
  #           group_by(driver) %>% 
  #           summarise(sen_tss_median=n(),
  #                     med=median(sen_tss_median, na.rm=T)),
  #           aes(label=sprintf("n=%s", sen_tss_median), x=0.025), 
  #           position=position_nudge(y=-0.15), colour="black", size=2.5)

#ggsave("D:/Dropbox/projects/riverTSS/figs/tss_drivers_hist_noylab.png", width=2.5, height=3, units="in", dpi=350)



```





```{r Fig4}

usa <- st_as_sf(map('usa', plot = FALSE, fill = TRUE)) %>%
  st_combine()  %>%
  st_transform(2163)
  
ggplot()+
  geom_sf(data=usa)

term_rates_plot <- term_rates %>%
   filter(frac_l !=0, frac_l_tidal !=0)

outlets <- flowline %>%
  filter(TermnlP %in% term_rates_plot$TermnlP) %>%
  group_by(TermnlP) %>%
  filter(Tidal==1) %>%
  filter(Pthlngt == min(Pthlngt, na.rm=T)) %>%
  st_point_on_surface() 

mapview(outlets)


ggplot(term_rates %>%
         filter(frac_l !=0, frac_l_tidal !=0) 
        # filter(length >=50 & length_tidal >=5) %>%
         )+ 
  geom_smooth(method="lm", aes(x=frac_l*100, y=frac_l_tidal*100, group=tp, color=tp)) +
    geom_point(aes(x=frac_l*100, y=frac_l_tidal*100, color=tp), size=2)  +
  scale_color_manual(values = c("#FDE725FF", "#482677FF")) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        legend.position="none",
        axis.text = element_text(size=16),
        axis.title = element_text(size=16))+
  xlab("% river length declining in TSS")+
  ylab("% tidal length declining in TSS") 
 # geom_abline(slope=1, intercept = 0, color="lightgrey", linetype=2) 


ggsave("D:/Dropbox/projects/riverTSS/figs/Fig_frac_dec_4.1.png", width=4, height=4 ,units="in", dpi=450)
 # xlim(0, 60) +



ggplot() +
  geom_sf(data=usa, fill="grey", color="transparent")+
 # geom_sf(data= huc2, fill="grey", color="black", lwd=0.25)+
  geom_sf(data=physio %>%
            filter(DIVISION=="ATLANTIC PLAIN"), fill="black", color="transparent", alpha=0.5) +

  geom_sf(data = flowline %>%
          inner_join(term_rates, by="TermnlP") %>%
          filter(frac_l !=0, frac_l_tidal !=0),
          aes(color= tp)) +
    theme_bw() +
  scale_color_manual(values =c("#FDE725FF", "#482677FF")) +
  geom_sf(data=outlets, color="black", size=1.4) +
    theme(legend.position = "none",
    line = element_blank(), 
    rect = element_blank(), 
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    plot.background = element_blank(),
    legend.text = element_text(size=9),
    legend.title = element_blank()) #+
            

ggsave("D:/Dropbox/projects/riverTSS/figs/Fig_map_tidal_4.1.png", width=6, height=4, units="in", dpi=350)


physio <- st_read("D:/GIS/physio.shp")  #%>%
  #group_by(DIVISION) %>%
  #summarise(AREA= sum(AREA)) %>%
  #st_combine() %>%
 #st_union(by_feature = F) 
 # ungroup()

ggplot()+
  geom_sf(data=physio)

ggplot()+
  geom_sf(data=physio %>%
            #group_by(DIVISION) %>%
            #st_union(by_feature = F) %>%
            filter(DIVISION=="ATLANTIC PLAIN") %>%
            st_combine() %>%
            st_union(by_feature = T) , fill="orange")

ggplot()+
  geom_sf(data=physio %>%
            #group_by(DIVISION) %>%
            #st_union(by_feature = F) %>%
            filter(DIVISION=="ATLANTIC PLAIN")
, fill="orange", color="transparent")


elev_test <- flowline_full %>%
    st_set_geometry(NULL) %>%
    inner_join(term_rates  %>%
               # filter(length >=50 & length_tidal >=5) %>%
               filter(frac_l_tidal !=0, frac_l !=0),
              ,by=c("TerminalPa"="TermnlP")) 
#  group_by(TermnlP)


  ggplot(elev_test) + #%>%
         #  filter(!TermnlP %in% c(350002977, 50001315))) +
  geom_histogram(aes((MAXELEVS*0.01),  fill=tp), color="black", alpha=0.5) +
  scale_y_log10() +
 #   scale_y_log10( breaks =10^(1:6),
  #              labels = 10^(1:6))+
  #    scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x),
   #           labels = scales::trans_format("log10", math_format(10^.x))) +
 # scale_fill_manual(values = c("dodgerblue", "goldenrod")) +
    scale_x_continuous(breaks=c(0,500,1000,1500,2000)) +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        legend.position="right",
        axis.text = element_text(size=16),
        axis.title = element_text(size=16)) +

  xlab("River elevation (m)")+
  ylab("Count")
  
ggsave("D:/Dropbox/projects/riverTSS/figs/Fig_elev.png", width=4.5, height=4.5 ,units="in", dpi=450)


  ggplot(elev_test %>%
           filter(MAXELEVS >=0))+
         #  mutate(MAXELEVS = ifelse(MAXELEVS ==0, 10, MAXELEVS))) + #%>%
           #filter(!TermnlP %in% c(350002977, 50001315))) +
  geom_density(aes((MAXELEVS*0.01),  fill=tp), color="black", alpha=0.7) +
 # scale_x_log10() +
 # scale_y_log10() +
   scale_x_log10( breaks =10^(-1:5),
                labels = 10^(-1:5))+
  #    scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x),
   #           labels = scales::trans_format("log10", math_format(10^.x))) +
  scale_fill_manual(values = c("#FDE725FF", "#482677FF")) +
  #scale_x_continuous(breaks=c(0,500,1000,1500,2000)) +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        legend.position="none",
        axis.text = element_text(size=18),
        axis.title = element_text(size=18)) +

  xlab("River elevation (m)")+
  ylab("Density")

  ggsave("D:/Dropbox/projects/riverTSS/figs/Fig_elev_new.png", width=4, height=3 ,units="in", dpi=450)

  
  
ggplot(elev_test %>%filter(SLOPE>0 & SLOPE <1)) +
  geom_density(aes(SLOPE*QE_MA*0.0283168*1000*9.8,  fill=tp), color="black", alpha=0.7) +
  scale_x_log10() +
 # scale_y_log10() +
 #  scale_x_log10( breaks =10^(-1:5),
 #               labels = 10^(-1:5))+
  #    scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x),
   #           labels = scales::trans_format("log10", math_format(10^.x))) +
  scale_fill_manual(values = c("#FDE725FF", "#482677FF")) +
  #scale_x_continuous(breaks=c(0,500,1000,1500,2000)) +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        legend.position="none",
        axis.text = element_text(size=16),
        axis.title = element_text(size=16)) +

  xlab("Stream Power")+
  ylab("Density")

  
  
  
  ########
ggplot(data=term_rates ) +
               # filter(length >=50 & length_tidal >=5) %>%
                #filter(frac_l_tidal !=0, frac_l !=0)) +
  geom_density(aes(storage_total_mm,  fill=tp), alpha=0.5) +
  scale_x_log10() +
 # scale_y_log10() +
 #   scale_y_log10( breaks =10^(1:6),
  #              labels = 10^(1:6))+
  #    scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x),
   #           labels = scales::trans_format("log10", math_format(10^.x))) +
  scale_color_manual(values = c("dodgerblue", "goldenrod")) 


ggplot(elev_test %>% filter(SLOPE>0 & SLOPE <1)) +
  geom_density(aes(x=(SLOPE*QE_MA*0.0283168*1000*9.8))) +
  scale_x_log10()

ggplot(elev_test %>% filter(SLOPE>0 & SLOPE <1)) +
  geom_point(aes(x=SLOPE, y=QE_MA))+
  scale_x_log10() +
  scale_y_log10()
      
```



```{r supp}


ggplot() +
  geom_sf(data= huc2, 
          fill="grey80", color="black", lwd=0.25)+
  geom_sf(data=flowline_trend %>% 
            mutate(Rate= ifelse(trend_median_05=="decreasing", abs(sen_tss_median), NA)),  aes(color=log10(Rate)), lwd=1.2)+
  scale_color_viridis_c() +
  theme_bw() +
    theme(legend.position = "right",
    line = element_blank(), 
    rect = element_blank(), 
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    plot.background = element_blank(),
    legend.text = element_text(size=9),
    legend.title = element_blank())

ggsave("D:/Dropbox/projects/riverTSS/figs/tss_sen.png", width=6, height=3, units="in", dpi=350)


```




```{r figs_UCSC}

nri %>%
  group_by(Year) %>%
  summarise(erosion = sum(water_erosion_tons, na.rm=T)) %>%
  mutate(erosion_Pg  = (erosion* 907.185*1000) / (10^6) / (10^6)) %>%
  ggplot()+
    geom_point(aes(x=Year, y=erosion_Pg), size=2.5) +
  theme_few() +
  theme(axis.title = element_text(size=14),
        axis.text = element_text(size=14)) +
  ylab("Soil erosion (Pg)") 
  
  ggsave("D:/Dropbox/projects/riverTSS/figs/total_erosion.png", width=3, height=3 ,units="in", dpi=350)

  
tss_sum <- read_feather("D:/Dropbox/projects/riverTSS/out/tss_ID_sum_v1.feather")
  
  ggplot(tss_sum %>%
         left_join(path_sum, by=c("LvlPthI" ="LevelPathI")) %>%
         filter(LvlPthI !=630001920 ) %>%
         filter(!ID %in% flag_reaches$ID) %>%
         filter(Name %in% c("Arkansas River", "Missouri River")) %>%
         mutate(trend = ifelse(Name=="Missouri River", "p>0.05", "p<0.05")) %>%
         group_by(LvlPthI) %>%
         mutate(Pthlngt = Pthlngt- min(Pthlngt)) %>%
         ungroup() %>%
         filter(LvlPthI== 350009839 & Pthlngt <1200 | LvlPthI ==550000017 & Pthlngt < 10000) %>%
          filter(LvlPthI ==350009839 & Pthlngt > 50 | LvlPthI== 550000017 & Pthlngt > 0)

    )+
  geom_line(aes(x=Pthlngt, y=mean), lwd=0.5)+
  scale_y_log10() +
  scale_x_reverse() +
    facet_wrap(~Name, scales="free", ncol=1, nrow=2) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.title = element_text(size=12),
        axis.text =  element_text(size=12),
        strip.text  = element_text(size=12)) +
  xlab("Distance from mouth (km)") +
  ylab("TSS (mg/L)") 
   
#
ggsave("D:/Dropbox/projects/riverTSS/figs/MO_Ark_profile.png", width=6, height=4, units="in", dpi=400)



ggplot() +
  geom_density(data=trends_tss_annual %>%
                 filter(!is.na(trend_median_05)) %>%
                mutate(sen_tss_median = abs(sen_tss_median)), 
               aes(sen_tss_median, fill=trend_median_05), alpha=0.6) +
  theme_few() +
  scale_x_log10() +
  scale_fill_manual(values=c("dodgerblue3", "goldenrod2"), name="") +
  xlab("Rate of change (mg/L/yr)") +
  ylab("Density") +
  theme(legend.position = c(0.78, 0.9),
        legend.background = element_blank())
  
ggsave("D:/Dropbox/projects/riverTSS/figs/TSS_rates.png", width=3, height=3, units="in", dpi=450)

trends_tss_annual %>%
filter(trend_median_05=="decreasing") %>%
  summarise(mean=mean(sen_tss_median))

ggplot() +

  geom_sf(data= huc2, fill="grey80", color="black", lwd=0.25)+
  geom_sf(data=flowline_trend %>%
            filter(Tidal==0) ,  aes(color=trend_median_05))+
  geom_sf(data=flowline %>%
            group_by(TermnlP) %>%
            filter(Pthlngt==min(Pthlngt)) %>%
            filter(Tidal==1) %>%
            st_point_on_surface(), color="black", size=1.5 )+
  theme_bw() +
  scale_color_manual(values =c("dodgerblue3", "goldenrod2", "grey60")) +
    theme(legend.position = c(0.98, 0.29),
    line = element_blank(), 
    rect = element_blank(), 
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    plot.background = element_blank(),
    legend.text = element_text(size=9),
    legend.title = element_blank()) 

ggsave("D:/Dropbox/projects/riverTSS/figs/coastal_outlets.png", width=6, height=3, units="in", dpi=350)



ggplot() +
  geom_density(data=flow_trends %>%
                 filter(!is.na(trend_median)) %>%
                mutate(sen_median_flow = abs(sen_median_flow)), 
               aes(sen_median_flow, fill=trend_median), alpha=0.6) +
  theme_few() + 
  scale_x_log10() +
  scale_fill_manual(values=c("dodgerblue3", "goldenrod2"), name="") +
  xlab("Rate of change (m3/s/yr)") +
  ylab("Density") +
  theme(legend.position = "right",
        legend.background = element_blank())
  
ggsave("D:/Dropbox/projects/riverTSS/figs/flow_rateChange.png", width=4, height=3, units="in", dpi=350)


```

