---
title: "reach_to_polygon"
author: "John Gardner"
date: "July 18, 2019"
output: html_document
---

```{r setup, include=FALSE}
library(earthEngineGrabR)
library(tidyverse)
library(feather)
library(knitr)
library(purrr)
library(reticulate)
library(googledrive)

#knitr::opts_chunk$set(echo = TRUE)
```



```{r reticulate_version}

reticulate_python <-'C:/Users/john/Anaconda2/envs/earthEngineGrabR/python.exe'
Sys.setenv(RETICULATE_PYTHON = reticulate_python)
use_condaenv("earthEngineGrabR", required=TRUE)

py_config()

```

```{python,eval=do_it}


# Import the Earth Engine Python Package
import time
import ee
#import os

# Initialize the Earth Engine object, using the authentication credentials.
ee.Initialize()

nhd_gee = ee.FeatureCollection("users/johngardner87/nhd_grwl_collapse");


HUC04 = ee.FeatureCollection("USGS/WBD/2017/HUC04")
#HUC08 = ee.FeatureCollection("USGS/WBD/2017/HUC08")

### define functions
def fdtFun(f):
    dt = ee.Image.constant(0).byte().paint(ee.FeatureCollection(f), 1).fastDistanceTransform()
    return dt.copyProperties(f, ['ID'])

def mfun(c, p):
    return ee.Image(c).min(p)

def minFun(f):
  return ee.Image(f.iterate(mfun, ee.Image(f.first())))

def idFun(c, p):
    c = ee.Image(c)
    p = ee.Image(p)
    return p.where(c.eq(minMap), ee.Number(c.get('ID')))

def maximum_no_of_tasks(MaxNActive, waitingPeriod):
  ##maintain a maximum number of active tasks
  time.sleep(10)
  ## initialize submitting jobs
  ts = list(ee.batch.Task.list())

  NActive = 0
  for task in ts:
       if ('RUNNING' in str(task) or 'READY' in str(task)):
           NActive += 1
  ## wait if the number of current active tasks reach the maximum number
  ## defined in MaxNActive
  while (NActive >= MaxNActive):
      time.sleep(waitingPeriod) # if reach or over maximum no. of active tasks, wait for 2min and check again
      ts = list(ee.batch.Task.list())
      NActive = 0
      for task in ts:
        if ('RUNNING' in str(task) or 'READY' in str(task)):
          NActive += 1
  return()

## loop through all HUC04 and output reach 
hucID = HUC04.aggregate_array('huc4').getInfo()

for x in range(0,len(hucID)):
#for x in range(0,2):
    
    #huc = HUC04.filter(ee.Filter.eq('huc4' , hucID[x]))
    huc = HUC04.filter(ee.Filter.stringStartsWith('huc4' , hucID[x]))
    
    nhdClip = nhd_gee.filterBounds(huc.geometry())

    nhdClip_buffer = nhdClip.geometry().buffer(2000)

##
    fdt = nhdClip.map(fdtFun)
    
    minMap = minFun(fdt)
    
    idImage = fdt.iterate(idFun, ee.Image(fdt.first()))
    
    COMID = ee.Image(idImage).rename('ID').clip(nhdClip_buffer)
##
    vectors = COMID.addBands(COMID).reduceToVectors(
        crs = COMID.projection(), 
        scale =  60, 
        geometry = huc, 
        geometryType = 'polygon',
        eightConnected= False,
        tileScale = 16,
        bestEffort = True,
        labelProperty = 'ID',
        maxPixels = 3000000000000000, 
        reducer = ee.Reducer.first()
        )

    
    dataOut = ee.batch.Export.table.toDrive(collection = vectors, \
                                              description = str(hucID[x]),\
                                              folder = 'reachPolygons_collapse',\
                                              fileFormat = 'shp')
    
    print(hucID[x])
  #Check how many existing tasks are running and take a break if it's >15  
    maximum_no_of_tasks(15, 60)
  #Send next task.
    dataOut.start()

#Make sure all Earth engine tasks are completed prior to moving on.  
maximum_no_of_tasks(1,300)
print('done')


```


## Including Plots

You can also embed plots, for example:

```{r combine, echo=FALSE}

library(rgdal)     
library(sf)

# load all reach polygon files
files <- dir("D:/GoogleDrive/reachPolygons_collapse", pattern = "*.shp", full.names = T)

CONUS_reach <- do.call(rbind, lapply(files, st_read))

# some get split at watershed boundaries. summarise is easy way to merge polygons with the same ID. this takes a few minutes
CONUS_reach_join <- CONUS_reach %>%
  group_by(ID) %>%
  summarise()

plot(st_geometry(CONUS_reach_join))  

#Also use mapview to inspect subsets the polygons to make sure they are non overlapping and look good

#st_write(CONUS_reach_join, "D:/GIS/river_networks/CONUS_nhd_reach_poly_collapse.shp")

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
