---
title: "SR_build"
author: "John Gardner"
date: "August 19, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(stringr)
library(tidyverse)
library(feather)
library(readr)
library(lubridate)

```


```{r loadSR}

### Create a cleaned surface reflectance database with band corrections, calculation of ### band combinations, and water color, brightness, saturation, etc.

# path to  surface reflectance pulls 
path2 <- "D:/GoogleDrive/WQP_RiverExport_v2"

# load functions
source("src/SR_build_functions.R")

# read in and merge SR pull
sr_us <- list.files(path=path2, pattern=".csv", full.names = T) %>%
  map_df(~ fread(., stringsAsFactors = F))

# apply function for cleaning data
sr_us_clean <- pull_clean(sr_us)


#correction_coef <- ls_correction(sr_us_clean)

# read correction coefficients to file
correction_coef<- read_csv("D:/Dropbox/projects/rivercolor/out/ls_poly_correction_coef.csv")

# filter poly coefficients with 1-99 % quantiles
correction_coef_99 <- correction_coef %>%
  filter(fit %in% c(NA, "98_quant")) %>%
  dplyr::select(-fit)

# Apply correction coefficients.This can take a while with large datasets
sr_clean <- sr_us_clean %>%
  mutate(rn = row_number()) %>%
  mutate(sat = as.character(sat)) %>%
  gather(red ,green, blue, nir, swir1, swir2, key='band', value='value') %>%
  group_by(band, sat) %>%
  left_join(correction_coef_99, by=c("band", "sat")) %>%
  mutate(value_cor=  coef2*value^ 2 + coef1*value + intercept) %>%
  ungroup() %>%
  mutate(value_cor = ifelse(value_cor <=0, value, value_cor)) %>%
  dplyr::select(-intercept, -coef1, -coef2) %>%
  pivot_wider(names_from = band,
              values_from = c("value", "value_cor"))  %>%
    rename_at(vars(starts_with("value_")),
           function(x) stringr::str_replace_all(x, "value_", "")) %>%
    rename_at(vars(red, green, blue, nir, swir1, swir2),function(x) paste0(x,"_raw")) %>%
    rename_at(vars(starts_with("cor")),            funs(stringr::str_replace_all(., "cor_", ""))) 

# apply function for transforming data, calculating color and band metics
sr_clean_all <- pull_transform(sr_clean, RGB=F, maxRGB=10000) 

# write data
#write_feather(sr_clean_all, "D:/Dropbox/projects/rivercolor/out/sr_clean_conus_v2.feather")


```



